### ISSUE TITLE
Hello Sir

### ISSUE THREAD

**Issue by mohdsaleem987** [victorkp/OpenCV-Square-Tracking-Android-JNI#1]
Hello sir,
I am new in open cv . Please help me out how i can import your project OpenCV-Square-Tracking-Android-JNI
in android gradle and also please tell me the process of import the open cv c++ file in android project

**Comment by victorkp** [comment]
This project pre-dates the Android Studio and the Android Gradle modules. The C++ code is just another source file that the Java code calls through JNI. 

You can follow the standard instructions for importing this Eclipse project into Android Studio: https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.jetbrains.com/help/idea/13.0/importing-eclipse-projects-into-intellij-idea.pdf&ved=0ahUKEwiY5tXxhMraAhUjVt8KHTRXA0YQFggnMAE&usg=AOvVaw2NTKLzeuzDjgW9k5K7z-Qe
